openapi: 3.2.0
info:
  title: ERCOT Public API Client/Developer Documentation NP3 233 CD API
  description: Client/Developer RESTFul web services documentation for ERCOT Market Information List (EMIL) products.
  version: '1.0'
servers:
- url: https://api.ercot.com/api/public-reports
security:
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: NP3-233-CD
  description: <b>Hourly Resource Outage Capacity</b><br/><br/>This report includes all approved and accepted Planned, Forced and Maintenance Resource outages EXCEPT Resource outages for retirement of old equipment, seasonal mothballed (during the outaged season), and mothballed. The outage capacity in this report reflects aggregated ACTIVE resource outaged capacity by Load Zone sourced from the Outage Scheduler (OS) for the next 168 hours and is published every hour. Columns 'C\' - 'F' consists of the aggregated outaged capacity of ALL the ACTIVE resource outages by Load Zone in the OS for each hour excluding the outages stated above, IRR resource outages, and new equipment outages. Columns 'G' - 'J' consists of the aggregated outaged capacity of ALL the ACTIVE IRR resource outages by Load Zone in the OS for each hour excluding the outages stated above, outages in columns 'C' - 'F' and new equipment outages. Columns 'K' - 'N' consists of the aggregated outaged capacity of ALL the ACTIVE New Equipment Energization resource outages by Load Zone. Note that this report contains OS data only and does not look at telemetry. It includes both entire resource outage and de-rates.
paths:
  /np3-233-cd/hourly_res_outage_cap:
    get:
      tags:
      - NP3-233-CD
      summary: Hourly Resource Outage Capacity
      description: Hourly Resource Outage Capacity
      operationId: getData_101
      parameters:
      - name: operatingDateFrom
        in: query
        description: Format - yyyy-MM-dd.
        schema:
          type: string
          format: yyyy-MM-dd
      - name: operatingDateTo
        in: query
        description: Format - yyyy-MM-dd.
        schema:
          type: string
          format: yyyy-MM-dd
      - name: hourEndingFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: hourEndingTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneSouthFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneSouthTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneNorthFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneNorthTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneWestFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneWestTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneHoustonFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalResourceMWZoneHoustonTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneSouthFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneSouthTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneNorthFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneNorthTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneWestFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneWestTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneHoustonFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalIRRMWZoneHoustonTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneSouthFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneSouthTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneNorthFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneNorthTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneWestFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneWestTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneHoustonFrom
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: totalNewEquipResourceMWZoneHoustonTo
        in: query
        description: 'Format - ###.'
        schema:
          type: integer
          format: '###'
      - name: postedDatetimeFrom
        in: query
        description: Format - yyyy-MM-ddTH24:mm:ss.
        schema:
          type: string
          format: yyyy-MM-ddTH24:mm:ss
      - name: postedDatetimeTo
        in: query
        description: Format - yyyy-MM-ddTH24:mm:ss.
        schema:
          type: string
          format: yyyy-MM-ddTH24:mm:ss
      - name: page
        in: query
        description: 'Format - ###. Page number of returned values in the collection.'
        schema:
          type: integer
          format: '###'
      - name: size
        in: query
        description: 'Format - ###. Number of returned items per page.'
        schema:
          type: integer
          format: '###'
      - name: sort
        in: query
        description: Format - abc123. Defines field by which to sort the returned resource values.
        schema:
          type: string
          format: abc123
      - name: dir
        in: query
        description: Format - abc123. Defines sort order of returned values based on the primary business key of the resource.
        schema:
          type: string
          format: abc123
      responses:
        '200':
          description: OK The operation completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
              example:
                _meta:
                  totalRecords: 0
                  pageSize: 0
                  totalPages: 0
                  currentPage: 0
                  query:
                    parameterCount: 0
                    parameters: {}
                    sortedBy: string
                report:
                  reportName: string
                  reportDisplayName: string
                  reportId: string
                  reportEMIL: string
                fields:
                - name: string
                  label: string
                  cardinality: 0
                  dataType: BOOLEAN
                  searchable: true
                  sortable: true
                  hasRange: true
                data: {}
                links:
                - rel: string
                  href: string
                  hreflang: string
                  media: string
                  title: string
                  type: string
                  deprecation: string
                  profile: string
                  name: string
        '400':
          description: The request operation failed. The request and/or one or more of its parameters are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
              example:
                timestamp: string
                code: 0
                status: string
                message: string
                data: {}
        '403':
          description: The request operation failed. You do not have access to the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
              example:
                timestamp: string
                code: 0
                status: string
                message: string
                data: {}
        '404':
          description: The request operation failed. The requested resource does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exception'
              example:
                timestamp: string
                code: 0
                status: string
                message: string
                data: {}
components:
  schemas:
    ReportMetadata:
      type: object
      properties:
        reportName:
          type: string
        reportDisplayName:
          type: string
        reportId:
          type: string
        reportEMIL:
          type: string
      description: Represents metadata for the specified object.
    Field:
      type: object
      properties:
        name:
          type: string
        label:
          type: string
        cardinality:
          type: integer
          format: int32
        dataType:
          enum:
          - BOOLEAN
          - VARCHAR
          - INTEGER
          - LONG
          - DOUBLE
          - DATE
          - DATETIME
          - TIME
          type: string
        searchable:
          type: boolean
        sortable:
          type: boolean
        hasRange:
          type: boolean
      description: Represents report data field.
    Exception:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string
        data:
          type: object
      description: Represents any exception encountered while access API endpoints.
    QueryMetadata:
      type: object
      properties:
        parameterCount:
          type: integer
          format: int32
        parameters:
          type: object
          additionalProperties:
            type: object
        sortedBy:
          type: string
      description: Represents query parameter summary for the specified query results.
    ResultMetadata:
      type: object
      properties:
        totalRecords:
          type: integer
          format: int64
        pageSize:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        currentPage:
          type: integer
          format: int32
        query:
          $ref: '#/components/schemas/QueryMetadata'
      description: Represents record and paging summary for the specified query results.
    Report:
      type: object
      properties:
        _meta:
          $ref: '#/components/schemas/ResultMetadata'
        report:
          $ref: '#/components/schemas/ReportMetadata'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        data:
          type: object
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
      description: Represents report data search results from any EMIL artifact report query.
    Link:
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
        hreflang:
          type: string
        media:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
